// auto-generated header to be imported in all cpp tests
#pragma once

#ifdef RDKIT_CATALOGS_BUILD
#undef RDKIT_CATALOGS_BUILD
#endif

#ifdef RDKIT_CHEMICALFEATURES_BUILD
#undef RDKIT_CHEMICALFEATURES_BUILD
#endif

#ifdef RDKIT_DATASTRUCTS_BUILD
#undef RDKIT_DATASTRUCTS_BUILD
#endif

#ifdef RDKIT_DISTGEOMETRY_BUILD
#undef RDKIT_DISTGEOMETRY_BUILD
#endif

#ifdef RDKIT_FORCEFIELD_BUILD
#undef RDKIT_FORCEFIELD_BUILD
#endif

#ifdef RDKIT_RDGEOMETRYLIB_BUILD
#undef RDKIT_RDGEOMETRYLIB_BUILD
#endif

#ifdef RDKIT_CHEMREACTIONS_BUILD
#undef RDKIT_CHEMREACTIONS_BUILD
#endif

#ifdef RDKIT_CHEMTRANSFORMS_BUILD
#undef RDKIT_CHEMTRANSFORMS_BUILD
#endif

#ifdef RDKIT_GRAPHMOL_BUILD
#undef RDKIT_GRAPHMOL_BUILD
#endif

#ifdef RDKIT_DEPICTOR_BUILD
#undef RDKIT_DEPICTOR_BUILD
#endif

#ifdef RDKIT_DESCRIPTORS_BUILD
#undef RDKIT_DESCRIPTORS_BUILD
#endif

#ifdef RDKIT_DISTGEOMHELPERS_BUILD
#undef RDKIT_DISTGEOMHELPERS_BUILD
#endif

#ifdef RDKIT_FILEPARSERS_BUILD
#undef RDKIT_FILEPARSERS_BUILD
#endif

#ifdef RDKIT_FILTERCATALOG_BUILD
#undef RDKIT_FILTERCATALOG_BUILD
#endif

#ifdef RDKIT_FINGERPRINTS_BUILD
#undef RDKIT_FINGERPRINTS_BUILD
#endif

#ifdef RDKIT_FMCS_BUILD
#undef RDKIT_FMCS_BUILD
#endif

#ifdef RDKIT_FORCEFIELDHELPERS_BUILD
#undef RDKIT_FORCEFIELDHELPERS_BUILD
#endif

#ifdef RDKIT_FRAGCATALOG_BUILD
#undef RDKIT_FRAGCATALOG_BUILD
#endif

#ifdef RDKIT_MMPA_BUILD
#undef RDKIT_MMPA_BUILD
#endif

#ifdef RDKIT_MOLALIGN_BUILD
#undef RDKIT_MOLALIGN_BUILD
#endif

#ifdef RDKIT_MOLCATALOG_BUILD
#undef RDKIT_MOLCATALOG_BUILD
#endif

#ifdef RDKIT_MOLCHEMICALFEATURES_BUILD
#undef RDKIT_MOLCHEMICALFEATURES_BUILD
#endif

#ifdef RDKIT_MOLDRAW2D_BUILD
#undef RDKIT_MOLDRAW2D_BUILD
#endif

#ifdef RDKIT_MOLHASH_BUILD
#undef RDKIT_MOLHASH_BUILD
#endif

#ifdef RDKIT_MOLINTERCHANGE_BUILD
#undef RDKIT_MOLINTERCHANGE_BUILD
#endif

#ifdef RDKIT_MOLTRANSFORMS_BUILD
#undef RDKIT_MOLTRANSFORMS_BUILD
#endif

#ifdef RDKIT_PARTIALCHARGES_BUILD
#undef RDKIT_PARTIALCHARGES_BUILD
#endif

#ifdef RDKIT_REDUCEDGRAPHS_BUILD
#undef RDKIT_REDUCEDGRAPHS_BUILD
#endif

#ifdef RDKIT_RGROUPDECOMPOSITION_BUILD
#undef RDKIT_RGROUPDECOMPOSITION_BUILD
#endif

#ifdef RDKIT_SHAPEHELPERS_BUILD
#undef RDKIT_SHAPEHELPERS_BUILD
#endif

#ifdef RDKIT_SLNPARSE_BUILD
#undef RDKIT_SLNPARSE_BUILD
#endif

#ifdef RDKIT_SMILESPARSE_BUILD
#undef RDKIT_SMILESPARSE_BUILD
#endif

#ifdef RDKIT_STRUCTCHECKER_BUILD
#undef RDKIT_STRUCTCHECKER_BUILD
#endif

#ifdef RDKIT_SUBGRAPHS_BUILD
#undef RDKIT_SUBGRAPHS_BUILD
#endif

#ifdef RDKIT_SUBSTRUCTMATCH_BUILD
#undef RDKIT_SUBSTRUCTMATCH_BUILD
#endif

#ifdef RDKIT_SUBSTRUCTLIBRARY_BUILD
#undef RDKIT_SUBSTRUCTLIBRARY_BUILD
#endif

#ifdef RDKIT_TRAJECTORY_BUILD
#undef RDKIT_TRAJECTORY_BUILD
#endif

#ifdef RDKIT_HC_BUILD
#undef RDKIT_HC_BUILD
#endif

#ifdef RDKIT_INFOTHEORY_BUILD
#undef RDKIT_INFOTHEORY_BUILD
#endif

#ifdef RDKIT_ALIGNMENT_BUILD
#undef RDKIT_ALIGNMENT_BUILD
#endif

#ifdef RDKIT_EIGENSOLVERS_BUILD
#undef RDKIT_EIGENSOLVERS_BUILD
#endif

#ifdef RDKIT_OPTIMIZER_BUILD
#undef RDKIT_OPTIMIZER_BUILD
#endif

#ifdef RDKIT_RDBOOST_BUILD
#undef RDKIT_RDBOOST_BUILD
#endif

#ifdef RDKIT_RDGENERAL_BUILD
#undef RDKIT_RDGENERAL_BUILD
#endif

#ifdef RDKIT_SIMDIVPICKERS_BUILD
#undef RDKIT_SIMDIVPICKERS_BUILD
#endif

#ifdef RDKIT_INCHI_BUILD
#undef RDKIT_INCHI_BUILD
#endif

#ifdef RDKIT_RDINCHILIB_BUILD
#undef RDKIT_RDINCHILIB_BUILD
#endif

#ifdef RDKIT_AVALONLIB_BUILD
#undef RDKIT_AVALONLIB_BUILD
#endif
