"""
Module containing FragCatalog, FragCatParams, FragCatGenerator,
and FragFPGenerator classes for fragment-based catalog generation and
fingerprinting.
"""

from typing import overload

import rdkit.Chem.rdchem
import rdkit.DataStructs.cDataStructs


class FragCatalog:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, params: FragCatParams) -> None: ...

    @overload
    def __init__(self, pickle: bytes) -> None: ...

    @overload
    def __init__(self, pickle: str) -> None: ...

    def GetNumEntries(self) -> int: ...

    def GetFPLength(self) -> int: ...

    def GetCatalogParams(self) -> FragCatParams: ...

    def Serialize(self) -> bytes: ...

    def GetBitDescription(self, idx: int) -> str: ...

    def GetBitOrder(self, idx: int) -> int: ...

    def GetBitFuncGroupIds(self, idx: int) -> list[int]: ...

    def GetBitEntryId(self, idx: int) -> int: ...

    def GetEntryBitId(self, idx: int) -> int: ...

    def GetEntryDescription(self, idx: int) -> str: ...

    def GetEntryOrder(self, idx: int) -> int: ...

    def GetEntryFuncGroupIds(self, idx: int) -> list[int]: ...

    def GetEntryDownIds(self, idx: int) -> list[int]: ...

    def GetBitDiscrims(self, idx: int) -> list[float]: ...

    def __getstate__(self) -> tuple[bytes, dict]: ...

    def __setstate__(self, arg: object, /) -> None: ...

class FragCatParams:
    def __init__(self, lLen: int, uLen: int, fgroupFilename: str, tol: float = 1e-08) -> None: ...

    def GetTypeString(self) -> str: ...

    def GetUpperFragLength(self) -> int: ...

    def GetLowerFragLength(self) -> int: ...

    def GetTolerance(self) -> float: ...

    def GetNumFuncGroups(self) -> int: ...

    def GetFuncGroup(self, fid: int) -> rdkit.Chem.rdchem.Mol: ...

    def Serialize(self) -> bytes: ...

class FragCatGenerator:
    def __init__(self) -> None: ...

    def AddFragsFromMol(self, mol: rdkit.Chem.rdchem.Mol, fcat: FragCatalog) -> int: ...

class FragFPGenerator:
    def __init__(self) -> None: ...

    def GetFPForMol(self, mol: rdkit.Chem.rdchem.Mol, fcat: FragCatalog) -> rdkit.DataStructs.cDataStructs.ExplicitBitVect: ...
