# Icons from Paul Mazaitis (goob@goob.com)

import os.path
import base64

# FIX: there's gotta be a better way to do this

# icon strings will all contain PNG data
base = os.path.split(__file__)[0]
exclaimPng="""iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAiElEQVR4nJWS0Q2DQAxDn6sOQNdg
xs7ECPAFI9wa7QbuB6pUSIJ6Vr6Ss2xfItv04Ja3JaS/Cd+nW8YpFAAYOizVCIQfG0uXQoNXOvAJ
sNcaR7btUiFNDNyjkzcMMMGYERQ33SRgLC4gECQuj+WYYf9TKd1xRoAGG8y1wjG0PUkPeNauktDX
+AApSkcyFaF47wAAAABJRU5ErkJggg==
"""
exclaimPng=base64.decodestring(exclaimPng)
notePng="""iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAn0lEQVR4nLWSMQ6DMAxF3686ZCTX
6N5bcQWWsnWGU7FzjTBmcwdKIBUEMdTTi2X72VJkZlyJ26Vq4L5hHdRkK5wbxiEblDVIndQCUpt4
ivTvtWe7Emb1Ak1KVo4Qiwapm/mbjXi31uwbMs4NWYPUQQBvVs9s1kxXDVXZkGaDnw3nN2w95Rts
HEQExxSpHIkPDY+n9S+F5ekh8Bv6+2/9AJr8TT6nI3uIAAAAAElFTkSuQmCC
"""
notePng=base64.decodestring(notePng)
blankPng="""iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xhBQAAAAZiS0dE
AP8A/wD/oL2nkwAAAAlwSFlzAAALEgAACxIB0t1+/AAAAAd0SU1FB9IFAQABAPplztAAAAASSURB
VHicY2AYBaNgFIwCCAAABBAAAVU3WtAAAAAASUVORK5CYII=
"""
blankPng=base64.decodestring(blankPng)
pngs = [
"""iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAIAAAAC64paAAABI0lEQVR4nGL8//8/AxJITWXABWbP
RhcBAAAA//9ihGuGa0tJOQlhzJljjszGNAIAAAD//2JB1glXigkgUnPmmKemIvQDAAAA//9iIkYn
mhFwNwIAAAD//2JCcyqR+iEAAAAA//9iwhNCeABEFwAAAP//YiLJWjTLAQAAAP//YiLHXhgAAAAA
//+iSDMAAAD//yJfc2oqAwAAAP//wqcZf1jMns0AAAAA//+iyNkAAAAA//+iSDMAAAD//2JiQEq3
RAK4egAAAAD//2LCzCvEAIguAAAAAP//YkIzjHhrGRgYAAAAAP//YoIbQ4x+iBq4YwEAAAD//8KX
n7FaiOxNAAAAAP//YqSkJAEAAAD//2L4jxukpOCR/P///38AAAAA//8DAEdifJMOtOqOAAAAAElF
TkSuQmCC""",
"""iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAIAAAAC64paAAABSklEQVR4nGL8//8/AxJITWXABWbP
RhcBAAAA//9ihGuGa0tJOQlhzJljPpsBKprKMBvTCAAAAAD//2JC1pmSchKuE91auClITgMAAAD/
/2JC1onTxQwMJ1NS4Grg+gEAAAD//2JCcyounXPmmEPUIKsEAAAA//9iwhNCcADXCQcQXQAAAAD/
/2IiaG0qw2w0BXAuAAAA//9iwm8nxKu4AAAAAP//IqAZ08HIAAAAAP//IqAZj87UVAYAAAAA///C
pxl/WMyezQAAAAD//yJgM34AAAAA//+iSDMAAAD//2JiYGCYM8ecJD1w9QAAAAD//2LCzCvEAIgu
AAAAAP//YkIzjHhrGRgYAAAAAP//YoIbQ4x+iBq4YwEAAAD//8KXn7FaiOxNAAAAAP//YqSkJAEA
AAD//2L4jxukpOCR/P///38AAAAA//8DAEnNi8GzxOioAAAAAElFTkSuQmCC""",
"""iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAIAAAAC64paAAABSElEQVR4nGL8//8/AxJITWXABWbP
RhcBAAAA//9ihGuGa0tJOQlhzJljPpsBKprKMBvTCAAAAAD//2JB1gnXhsVahlSIEampCP0AAAAA
//9iIkYnuhEwNwIAAAD//2JCcyqR+iEAAAAA//9iwhNCeABEFwAAAP//YiLJWgYGhpMpKXA2AAAA
//9iIV7PnDnmDAwMDHMYUlJOQtgAAAAA//8ioBlND5osAAAA//8ioHnOHHNcnkpNZQAAAAD//8Kn
GX9YzJ7NAAAAAP//YsJvM34AAAAA//+iSDMAAAD//2JiYGCABgnRAK4eAAAA//9iwswrxACILgAA
AAD//2JCM4x4axkYGAAAAAD//2KCG0OMfogauGMBAAAA///Cl5+xWojsTQAAAAD//2KkpCQBAAAA
//9i+I8bpKTgkfz///9/AAAAAP//AwBjB4hCQ8GmhQAAAABJRU5ErkJggg==""",
"""iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAIAAAAC64paAAABR0lEQVR4nGL8//8/AxJITWXABWbP
RhcBAAAA//9ihGuGa0tJOQlhzJljPpsBKprKMBvTCAAAAAD//2JB1gnXhsVahlSIEampCP0AAAAA
//9iIkYnuhEwNwIAAAD//2JCcyqR+iEAAAAA//9iwhNCeABEFwAAAP//YiLJWjTLAQAAAP//YiLH
XhgAAAAA//+iSDMAAAD//yKgOZVh9smUFOxSqQwAAAAA//9iwaMTEhZz5pjPYTCHcM3nzIHLzp7N
AAAAAP//wqcZ2Qg0UxjmMDAwMAAAAAD//yKsGaspEAYAAAD//2JC5pAKAAAAAP//YsLMK8QAiC4A
AAAA//9iQnMJQYCsEgAAAP//YoIbQ4x+iBq4YwEAAAD//8KXn7FaiOxNAAAAAP//YqSkJAEAAAD/
/2L4jxukpOCR/P///38AAAAA//8DAL5XiErdO1ybAAAAAElFTkSuQmCC""",
"""iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAIAAAAC64paAAABP0lEQVR4nGL8//8/AxJITWXABWbP
RhcBAAAA//9ihGuGa0tJOQlhzJljPpsBKprKMBvTCAAAAAD//2JB1gnXhsVahlSIEampCP0AAAAA
//9iIkYnuhEwNwIAAAD//2JCcyqR+iEAAAAA//9iwhNCeABEFwAAAP//YiLJWjTLAQAAAP//YiLH
XhgAAAAA//+iSDMAAAD//yJfc2oqAwAAAP//wqc5JeUkPG1ggtmzGQAAAAD//yJgM379AAAAAP//
IsrZJ1NSsIoDAAAA//9iYmBgmDPHHL/laArgbgEAAAD//2LCzCtY9aM5HqILAAAA//+COhu/5cj6
kU0BAAAA//9ightDUD8DzPNwxwIAAAD//8KXn5EB3GhkbwIAAAD//2KkpCQBAAAA//9i+I8bpKTg
kfz///9/AAAAAP//AwB3Y4VopK2lJQAAAABJRU5ErkJggg==""",
"""iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAIAAAAC64paAAABNElEQVR4nGL8//8/AxJITWXABWbP
RhcBAAAA//9ihGuGa0tJOQlhzJljPpsBKprKMBvTCAAAAAD//2JB1gnXhsVahlSIEampCP0AAAAA
//9iIkYnuhEwNwIAAAD//2JCcyqR+iEAAAAA//9iwhNCeABEFwAAAP//YiLJWjTLAQAAAP//YiLH
XhgAAAAA//+iSDMAAAD//yJfc2oqAwAAAP//Il/z7NkMAAAAAP//osjZAAAAAP//okgzAAAA//9i
YmBgmDPHnCQ98HQOAAAA//9iwswrxACILgAAAAD//4I6m3jL4dYyMDAAAAAA//9ightDjH6ITrhj
AQAAAP//YkJ2xpw55riMSGWYjaaTgYEBAAAA//9ipKQkAQAAAP//YviPG6Sk4JH8////fwAAAAD/
/wMALOx1ULTw2eAAAAAASUVORK5CYII=""",
"""iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAIAAAAC64paAAABOklEQVR4nGL8//8/AxJITWXABWbP
RhcBAAAA//9ihGuGa0tJOQlhzJljPpsBKprKMBvTCAAAAAD//2JB1gnXhsVahlSIEampCP0AAAAA
//9iIkYnuhEwNwIAAAD//2JCcyqR+iEAAAAA//9iwhNCeABEFwAAAP//YiLJWjTLAQAAAP//YiLH
XhgAAAAA//+iSDMAAAD//yJfc2oqAwAAAP//wqkZOYVgBbNnMwAAAAD//8Kuec4cc2IsBwAAAP//
wmkzfmshAAAAAP//YsK0h6CD4ekcAAAA//9iQssrBHVC3TWbgYGBAQAAAP//YoLrwXQCfmsZGBgA
AAAA//+CZkl4IiXGwXDHAgAAAP//wpKfserHmp8BAAAA//9ipKQkAQAAAP//YviPG6Sk4JH8////
fwAAAAD//wMATPaCTtcC3qcAAAAASUVORK5CYII=""",
"""iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAIAAAAC64paAAABNUlEQVR4nGL8//8/AxJITWXABWbP
RhcBAAAA//9ihGuGa0tJOQlhzJljPpsBKprKMBvTCAAAAAD//2JB1gnXhsVahlSIEampCP0AAAAA
//9iIkYnuhEwNwIAAAD//2JCcyqR+iEAAAAA//9iwhNCeABEFwAAAP//YiLJWjTLAQAAAP//YiLH
XhgAAAAA//+iSDMAAAD//8Kpec4cc/w6U1MZAAAAAP//YsGlBzlUsYLZsxkAAAAA//9iIVUPMgAA
AAD//2JhQE2GJAEAAAAA//8iJ8Dg6RwAAAD//2LCzCvEAIguAAAAAP//YkIzjHhrGRgYAAAAAP//
YoIbQ4x+iBq4YwEAAAD//8KSn7EGHtb8DAAAAP//YqSkJAEAAAD//2L4jxukpOCR/P///38AAAAA
//8DAOZre3eEryjuAAAAAElFTkSuQmCC""",
"""iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAIAAAAC64paAAABPElEQVR4nGL8//8/AxJITWXABWbP
RhcBAAAA//9ihGuGa0tJOQlhzJljPpsBKprKMBvTCAAAAAD//2JB1gnXhsVahlSIEampCP0AAAAA
//9iIkYnuhEwNwIAAAD//2JCcyqR+iEAAAAA//9iwhNCeABEFwAAAP//YiJDJ9xyAAAAAP//YoFw
UudAA4F49zMwMAAAAAD//2JBM4wkUwAAAAD//2LB5SS4KbhAaioDAAAA//9C14xpCk4FsxkAAAAA
//8iJ8DgAAAAAP//okgzAAAA//9iYkBKt0QCuHoAAAAA//9iwswrxACILgAAAAD//2JCM4x4axkY
GAAAAAD//2KCG0OMfogauGMBAAAA///Ckp+xRhLW/AwAAAD//2KkpCQBAAAA//9i+I8bpKTgkfz/
//9/AAAAAP//AwDGXn4icclPLAAAAABJRU5ErkJggg==""",
"""iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAIAAAAC64paAAABM0lEQVR4nGL8//8/AxJITWXABWbP
RhcBAAAA//9ihGuGa0tJOQlhzJljPpsBKprKMBvTCAAAAAD//2LCpRPdWoZUiEHITgMAAAD//2KC
8+GW4AFo+gEAAAD//2JCFp3NkDpnjjkx+iEAAAAA//9iQgshYvTDLQcAAAD//2LCdDBB/XD1AAAA
AP//YiJoCR4AAAAA///CrplIxwMAAAD//8JpM8HAT01lAAAAAP//wuds/Ppnz2YAAAAA//+iyM8A
AAAA//+iSDMAAAD//2JiQEq3RAK4egAAAAD//2LCzCvEAIguAAAAAP//gmUMoi1HVgkAAAD//2KC
G0OMfogauGMBAAAA///Ckp+xxhDW/AwAAAD//2KkpCQBAAAA//9i+I8bpKTgkfz///9/AAAAAP//
AwBnqXyGE6mDswAAAABJRU5ErkJggg==""",
"""iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAIAAAAC64paAAABIUlEQVR4nGL8//8/AxJITWXABWbP
RhcBAAAA//9ihGuGa5vNAGWlMsxGZmMaAQAAAP//YkLWOZshFa4a3VqYFLLTAAAAAP//YkLWidPF
SEYg6wcAAAD//2JCcyqR+iEAAAAA//9iwhNCeABEFwAAAP//YiLJWjTLAQAAAP//YiLHXhgAAAAA
//+iSDMAAAD//yJfc2oqAwAAAP//wqcZf1jMns0AAAAA//+iyNkAAAAA//+iSDMAAAD//2JiQEq3
RAK4egAAAAD//2LCzCvEAIguAAAAAP//gmUMoi1HVgkAAAD//2KCG0OMfogauGMBAAAA///Cl5+x
WojsTQAAAAD//2KkpCQBAAAA//9i+I8bpKTgkfz///9/AAAAAP//AwD+63E5bWBkTAAAAABJRU5E
rkJggg=="""]
for i in range(len(pngs)):
  pngs[i] = base64.decodestring(pngs[i])
