#line 2 "/scratch/RDKit_git/Code/GraphMol/SmilesParse/lex.yysmiles.cpp"

#line 4 "/scratch/RDKit_git/Code/GraphMol/SmilesParse/lex.yysmiles.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yysmiles_restart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yysmiles_restart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yysmiles_restart (FILE *input_file ,yyscan_t yyscanner );
void yysmiles__switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE yysmiles__create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void yysmiles__delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void yysmiles__flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void yysmiles_push_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void yysmiles_pop_buffer_state (yyscan_t yyscanner );

static void yysmiles_ensure_buffer_stack (yyscan_t yyscanner );
static void yysmiles__load_buffer_state (yyscan_t yyscanner );
static void yysmiles__init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER yysmiles__flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE yysmiles__scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE yysmiles__scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE yysmiles__scan_bytes (yyconst char *bytes,yy_size_t len ,yyscan_t yyscanner );

void *yysmiles_alloc (yy_size_t ,yyscan_t yyscanner );
void *yysmiles_realloc (void *,yy_size_t ,yyscan_t yyscanner );
void yysmiles_free (void * ,yyscan_t yyscanner );

#define yy_new_buffer yysmiles__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yysmiles_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yysmiles__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yysmiles_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yysmiles__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yysmiles_wrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 181
#define YY_END_OF_BUFFER 182
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[246] =
    {   0,
        0,    0,    0,    0,  182,  180,  179,  162,  176,  171,
      172,  144,  170,  169,  175,  168,  177,  178,  163,  180,
      161,    6,  123,  124,  129,  133,  132,  125,  126,  127,
      128,  173,  167,  134,  135,  136,  137,  138,  139,  166,
      180,  145,  180,  123,  124,  180,  180,  129,  180,  133,
      132,   16,  180,  180,  125,  126,  127,  180,  128,  180,
       87,   20,   69,  180,   35,  180,  174,  180,  139,  180,
      164,  165,    0,    0,    0,    0,    0,    0,  131,  130,
      167,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   84,   43,   13,   90,   15,   30,   80,

       74,   51,    9,  102,   78,   92,   17,   44,   53,   93,
       91,  107,   24,   21,   50,   26,  100,  105,   61,   63,
       94,   58,   23,  109,   95,   82,   28,   59,   29,    7,
       67,   75,   62,  103,   45,   72,   32,   52,    8,   98,
       66,  111,  110,   96,   12,   22,   38,  104,   11,   37,
       55,   10,  108,   25,   97,   88,  113,   71,   86,   77,
       42,   56,   79,   54,   73,   89,   83,   33,   70,   99,
      106,   41,   81,   40,   47,   18,   31,  101,   14,   57,
       46,   34,   68,   60,   39,   48,   85,   19,   76,   64,
      112,    0,   49,   65,   27,   36,  141,  142,  140,  143,

        2,    4,    5,    3,    1,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      116,  120,  114,  122,  119,  118,  121,  117,  115,  149,
      154,  147,  152,  156,  150,  158,  157,  151,  155,  160,
      146,  153,  148,  159,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    1,    1,    4,    1,    5,    1,    6,    7,
        8,    9,   10,    1,   11,   12,   13,   14,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   16,    1,   17,
       18,   19,    1,   20,   21,   22,   23,   24,   25,   26,
       27,   28,   29,    1,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
       46,   47,   48,    1,    1,    1,   49,   50,   51,   52,

       53,   54,   55,   56,   57,    1,   58,   59,   60,   61,
       62,   63,   64,   65,   66,   67,   68,   69,    1,    1,
       70,    1,    1,    1,    1,   71,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[72] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1
    } ;

static yyconst flex_uint16_t yy_base[246] =
    {   0,
        0,    0,   66,    0,  242,  312,  312,  312,  312,  312,
      312,  312,  312,  222,  312,  312,  312,  312,  312,  228,
      312,  113,  172,  177,  312,  312,  312,  312,  312,  312,
      312,  312,  188,  312,  312,  312,  312,  312,  312,  312,
      131,  312,   62,  118,  135,   70,    8,   78,   26,  124,
       16,  169,  142,  153,  169,   57,  178,  198,  207,  220,
      165,  312,  312,  176,  174,   19,  312,  157,   88,  164,
      312,  312,  272,  185,  178,  184,  173,  178,  312,  312,
      312,  146,  137,   36,  134,  126,  116,   75,  126,  126,
       70,  125,  107,  312,  312,  312,  312,  312,  312,  312,

      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  234,  312,  312,  312,  312,  312,  312,  312,  312,

      312,  312,  312,  312,  312,  166,  160,  155,  154,  152,
      150,  144,  143,  142,  140,  138,  133,  112,   79,   77,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312
    } ;

static yyconst flex_int16_t yy_def[246] =
    {   0,
      245,    1,    1,    3,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,

      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,

      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,    0
    } ;

static yyconst flex_uint16_t yy_nxt[384] =
    {   0,
        6,    7,    6,    8,    9,    6,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,    6,   22,
        6,   23,   24,    6,    6,   25,    6,   26,   27,    6,
        6,    6,   28,   29,   30,    6,    6,   31,    6,    6,
        6,    6,    6,    6,    6,   32,   33,    6,    6,   34,
       35,    6,    6,    6,    6,    6,    6,    6,    6,    6,
       36,   37,   38,    6,    6,   39,    6,    6,    6,    6,
       40,   41,  120,  121,  127,  122,  135,  128,  129,  195,
      136,   42,  244,  196,  243,  208,   43,   44,   45,   46,
       47,   48,   49,   50,   51,   52,   53,   54,   55,   56,

       57,  209,   58,   59,   60,   61,   62,   63,   64,   65,
       66,  157,   94,   67,   68,   73,   95,  242,   73,  117,
       96,   97,  158,  217,  218,  213,   98,   99,  100,  101,
      123,   69,   70,   74,   75,  118,  124,  125,  241,  119,
      198,  214,  126,  240,  199,  239,   76,  238,  237,  236,
       77,   78,   82,   83,   84,  235,   85,  234,   86,  233,
      232,   87,   88,   89,   90,  231,  102,   91,   92,   93,
      103,  230,  220,  104,  105,  106,  130,  131,  132,  219,
      216,  215,   79,  107,  212,  133,  108,  109,  110,  134,
      138,  211,  210,   80,  111,  112,  113,  207,  139,  114,

      115,  206,  116,  143,  144,  205,  140,  145,  204,  141,
      142,  203,  202,  146,  147,  201,  200,  149,  150,  148,
      151,  152,  197,  194,  153,  154,  159,  160,  193,  161,
      155,  156,  192,  137,   81,   80,   79,  162,   72,  163,
       71,  245,  164,  245,  165,  166,  167,  168,  245,  245,
      169,  170,  171,  172,  245,  245,  175,  176,  173,  177,
      245,  178,  245,  179,  245,  174,  180,  181,  183,  184,
      185,  182,  186,  245,   73,  187,  188,   73,  189,  190,
      245,  245,  245,  221,  245,  191,  245,  245,  245,  222,
      245,  245,   74,   75,  223,  224,  225,  226,  245,  227,

      228,  229,  245,  245,  245,   76,  245,  245,  245,   77,
       78,    5,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245
    } ;

static yyconst flex_int16_t yy_chk[384] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,   47,   47,   49,   47,   51,   49,   49,   66,
       51,    3,  220,   66,  219,   84,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,   84,    3,    3,    3,    3,    3,    3,    3,    3,
        3,   56,   43,    3,    3,   22,   43,  218,   22,   46,
       43,   43,   56,   91,   91,   88,   43,   43,   43,   43,
       48,    3,    3,   22,   22,   46,   48,   48,  217,   46,
       69,   88,   48,  216,   69,  215,   22,  214,  213,  212,
       22,   22,   41,   41,   41,  211,   41,  210,   41,  209,
      208,   41,   41,   41,   41,  207,   44,   41,   41,   41,
       44,  206,   93,   44,   44,   44,   50,   50,   50,   92,
       90,   89,   44,   45,   87,   50,   45,   45,   45,   50,
       53,   86,   85,   45,   45,   45,   45,   83,   53,   45,

       45,   82,   45,   54,   54,   78,   53,   54,   77,   53,
       53,   76,   75,   54,   54,   74,   70,   55,   55,   54,
       55,   55,   68,   65,   55,   55,   57,   57,   64,   57,
       55,   55,   61,   52,   33,   24,   23,   57,   20,   57,
       14,    5,   57,    0,   57,   57,   58,   58,    0,    0,
       58,   58,   58,   58,    0,    0,   59,   59,   58,   59,
        0,   59,    0,   59,    0,   58,   59,   59,   60,   60,
       60,   59,   60,    0,   73,   60,   60,   73,   60,   60,
        0,    0,    0,  192,    0,   60,    0,    0,    0,  192,
        0,    0,   73,   73,  192,  192,  192,  192,    0,  192,

      192,  192,    0,    0,    0,   73,    0,    0,    0,   73,
       73,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "smiles.ll"
#line 6 "smiles.ll"

// $Id$
//
//  Copyright (C) 2001-2010 Randal Henne, Greg Landrum and Rational Discovery LLC
//
//   @@ All Rights Reserved  @@
//

#include <cstdio>
#ifdef WIN32
#include <io.h>
#endif

#include <RDGeneral/Exceptions.h>
#include <RDGeneral/types.h>
#include <GraphMol/GraphMol.h>
#include <GraphMol/Atom.h>
#include <GraphMol/Bond.h>
#include <GraphMol/PeriodicTable.h>
#include <GraphMol/RDKitQueries.h>

#include <string>
#include <cstring>
#include "smiles.tab.hpp"

using namespace RDKit;

#define YY_FATAL_ERROR(msg) smiles_lexer_error(msg)

void smiles_lexer_error(const char *msg) {
     BOOST_LOG(rdErrorLog) << msg<<std::endl;
     throw ValueErrorException(msg);
}

size_t setup_smiles_string(const std::string &text,yyscan_t yyscanner){
//  YY_BUFFER_STATE buff=yysmiles__scan_string(text.c_str()+pos,yyscanner);
  // Faster implementation of yysmiles__scan_string that handles trimming
  YY_BUFFER_STATE b;
  char *buf;
  yyconst char * yybytes = text.c_str();
  yy_size_t _yybytes_len=text.size(), n, start, end;
  /* Get memory for full buffer, including space for trailing EOB's. */
  n = _yybytes_len + 2;
  buf = (char *) yysmiles_alloc(n ,yyscanner );
  if ( ! buf )
    smiles_lexer_error( "out of dynamic memory in yysmiles__scan_bytes()" );

  // ltrim

  for(start = 0 ; start < _yybytes_len; ++start) {
    if (yybytes[start] > 32) break;
  }
  for(end = _yybytes_len ; end > start; --end) {
    if (yybytes[end] > 32) break;
  }

  _yybytes_len = end-start+1;
  n = _yybytes_len + 2;
  memcpy(buf, yybytes+start, _yybytes_len);


  buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

  b = yysmiles__scan_buffer(buf,n ,yyscanner);
  if ( ! b )
    smiles_lexer_error( "bad buffer in yysmiles__scan_bytes()" );

  /* It's okay to grow etc. this buffer, and we should throw it
   * away when we're done.
   */
  b->yy_is_our_buffer = 1;


  POSTCONDITION(b,"invalid buffer");
  return start;

}

#line 691 "/scratch/RDKit_git/Code/GraphMol/SmilesParse/lex.yysmiles.cpp"

#define INITIAL 0
#define IN_ATOM_STATE 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    yy_size_t yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
int yysmiles_lex_init (yyscan_t* scanner);

int yysmiles_lex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yysmiles_lex_destroy (yyscan_t yyscanner );

int yysmiles_get_debug (yyscan_t yyscanner );

void yysmiles_set_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE yysmiles_get_extra (yyscan_t yyscanner );

void yysmiles_set_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *yysmiles_get_in (yyscan_t yyscanner );

void yysmiles_set_in  (FILE * _in_str ,yyscan_t yyscanner );

FILE *yysmiles_get_out (yyscan_t yyscanner );

void yysmiles_set_out  (FILE * _out_str ,yyscan_t yyscanner );

yy_size_t yysmiles_get_leng (yyscan_t yyscanner );

char *yysmiles_get_text (yyscan_t yyscanner );

int yysmiles_get_lineno (yyscan_t yyscanner );

void yysmiles_set_lineno (int _line_number ,yyscan_t yyscanner );

int yysmiles_get_column  (yyscan_t yyscanner );

void yysmiles_set_column (int _column_no ,yyscan_t yyscanner );

YYSTYPE * yysmiles_get_lval (yyscan_t yyscanner );

void yysmiles_set_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yysmiles_wrap (yyscan_t yyscanner );
#else
extern int yysmiles_wrap (yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  ,yyscan_t yyscanner);
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yysmiles_lex \
               (YYSTYPE * yylval_param ,yyscan_t yyscanner);

#define YY_DECL int yysmiles_lex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yysmiles_ensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yysmiles__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		yysmiles__load_buffer_state(yyscanner );
		}

	{
#line 86 "smiles.ll"


#line 970 "/scratch/RDKit_git/Code/GraphMol/SmilesParse/lex.yysmiles.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 246 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 312 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
#line 89 "smiles.ll"
case 2:
#line 90 "smiles.ll"
case 3:
#line 91 "smiles.ll"
case 4:
#line 92 "smiles.ll"
case 5:
YY_RULE_SETUP
#line 92 "smiles.ll"
{ return CHI_CLASS_TOKEN; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 94 "smiles.ll"
{ return AT_TOKEN; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 97 "smiles.ll"
{ yylval->atom = new Atom(2); return ATOM_TOKEN; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 98 "smiles.ll"
{ yylval->atom = new Atom(3); return ATOM_TOKEN; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 99 "smiles.ll"
{ yylval->atom = new Atom(4); return ATOM_TOKEN; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 100 "smiles.ll"
{ yylval->atom = new Atom(10); return ATOM_TOKEN; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 101 "smiles.ll"
{ yylval->atom = new Atom(11); return ATOM_TOKEN; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 102 "smiles.ll"
{ yylval->atom = new Atom(12); return ATOM_TOKEN; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 103 "smiles.ll"
{ yylval->atom = new Atom(13); return ATOM_TOKEN; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 104 "smiles.ll"
{ yylval->atom = new Atom(14); return ATOM_TOKEN; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 105 "smiles.ll"
{ yylval->atom = new Atom(18); return ATOM_TOKEN; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 106 "smiles.ll"
{ yylval->atom = new Atom(19); return ATOM_TOKEN; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 107 "smiles.ll"
{ yylval->atom = new Atom(20); return ATOM_TOKEN; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 108 "smiles.ll"
{ yylval->atom = new Atom(21); return ATOM_TOKEN; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 109 "smiles.ll"
{ yylval->atom = new Atom(22); return ATOM_TOKEN; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 110 "smiles.ll"
{ yylval->atom = new Atom(23); return ATOM_TOKEN; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 111 "smiles.ll"
{ yylval->atom = new Atom(24); return ATOM_TOKEN; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 112 "smiles.ll"
{ yylval->atom = new Atom(25); return ATOM_TOKEN; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 113 "smiles.ll"
{ yylval->atom = new Atom(26); return ATOM_TOKEN; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 114 "smiles.ll"
{ yylval->atom = new Atom(27); return ATOM_TOKEN; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 115 "smiles.ll"
{ yylval->atom = new Atom(28); return ATOM_TOKEN; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 116 "smiles.ll"
{ yylval->atom = new Atom(29); return ATOM_TOKEN; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 117 "smiles.ll"
{ yylval->atom = new Atom(30); return ATOM_TOKEN; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 118 "smiles.ll"
{ yylval->atom = new Atom(31); return ATOM_TOKEN; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 119 "smiles.ll"
{ yylval->atom = new Atom(32); return ATOM_TOKEN; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 120 "smiles.ll"
{ yylval->atom = new Atom(33); return ATOM_TOKEN; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 121 "smiles.ll"
{ yylval->atom = new Atom(34); return ATOM_TOKEN; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 122 "smiles.ll"
{ yylval->atom = new Atom(36); return ATOM_TOKEN; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 123 "smiles.ll"
{ yylval->atom = new Atom(37); return ATOM_TOKEN; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 124 "smiles.ll"
{ yylval->atom = new Atom(38); return ATOM_TOKEN; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 125 "smiles.ll"
{ yylval->atom = new Atom(39); return ATOM_TOKEN; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 126 "smiles.ll"
{ yylval->atom = new Atom(40); return ATOM_TOKEN; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 127 "smiles.ll"
{ yylval->atom = new Atom(41); return ATOM_TOKEN; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 128 "smiles.ll"
{ yylval->atom = new Atom(42); return ATOM_TOKEN; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 129 "smiles.ll"
{ yylval->atom = new Atom(43); return ATOM_TOKEN; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 130 "smiles.ll"
{ yylval->atom = new Atom(44); return ATOM_TOKEN; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 131 "smiles.ll"
{ yylval->atom = new Atom(45); return ATOM_TOKEN; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 132 "smiles.ll"
{ yylval->atom = new Atom(46); return ATOM_TOKEN; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 133 "smiles.ll"
{ yylval->atom = new Atom(47); return ATOM_TOKEN; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 134 "smiles.ll"
{ yylval->atom = new Atom(48); return ATOM_TOKEN; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 135 "smiles.ll"
{ yylval->atom = new Atom(49); return ATOM_TOKEN; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 136 "smiles.ll"
{ yylval->atom = new Atom(50); return ATOM_TOKEN; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 137 "smiles.ll"
{ yylval->atom = new Atom(51); return ATOM_TOKEN; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 138 "smiles.ll"
{ yylval->atom = new Atom(52); return ATOM_TOKEN; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 139 "smiles.ll"
{ yylval->atom = new Atom(54); return ATOM_TOKEN; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 140 "smiles.ll"
{ yylval->atom = new Atom(55); return ATOM_TOKEN; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 141 "smiles.ll"
{ yylval->atom = new Atom(56); return ATOM_TOKEN; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 142 "smiles.ll"
{ yylval->atom = new Atom(57); return ATOM_TOKEN; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 143 "smiles.ll"
{ yylval->atom = new Atom(58); return ATOM_TOKEN; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 144 "smiles.ll"
{ yylval->atom = new Atom(59); return ATOM_TOKEN; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 145 "smiles.ll"
{ yylval->atom = new Atom(60); return ATOM_TOKEN; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 146 "smiles.ll"
{ yylval->atom = new Atom(61); return ATOM_TOKEN; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 147 "smiles.ll"
{ yylval->atom = new Atom(62); return ATOM_TOKEN; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 148 "smiles.ll"
{ yylval->atom = new Atom(63); return ATOM_TOKEN; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 149 "smiles.ll"
{ yylval->atom = new Atom(64); return ATOM_TOKEN; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 150 "smiles.ll"
{ yylval->atom = new Atom(65); return ATOM_TOKEN; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 151 "smiles.ll"
{ yylval->atom = new Atom(66); return ATOM_TOKEN; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 152 "smiles.ll"
{ yylval->atom = new Atom(67); return ATOM_TOKEN; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 153 "smiles.ll"
{ yylval->atom = new Atom(68); return ATOM_TOKEN; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 154 "smiles.ll"
{ yylval->atom = new Atom(69); return ATOM_TOKEN; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 155 "smiles.ll"
{ yylval->atom = new Atom(70); return ATOM_TOKEN; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 156 "smiles.ll"
{ yylval->atom = new Atom(71); return ATOM_TOKEN; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 157 "smiles.ll"
{ yylval->atom = new Atom(72); return ATOM_TOKEN; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 158 "smiles.ll"
{ yylval->atom = new Atom(73); return ATOM_TOKEN; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 159 "smiles.ll"
{ yylval->atom = new Atom(74); return ATOM_TOKEN; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 160 "smiles.ll"
{ yylval->atom = new Atom(75); return ATOM_TOKEN; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 161 "smiles.ll"
{ yylval->atom = new Atom(76); return ATOM_TOKEN; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 162 "smiles.ll"
{ yylval->atom = new Atom(77); return ATOM_TOKEN; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 163 "smiles.ll"
{ yylval->atom = new Atom(78); return ATOM_TOKEN; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 164 "smiles.ll"
{ yylval->atom = new Atom(79); return ATOM_TOKEN; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 165 "smiles.ll"
{ yylval->atom = new Atom(80); return ATOM_TOKEN; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 166 "smiles.ll"
{ yylval->atom = new Atom(81); return ATOM_TOKEN; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 167 "smiles.ll"
{ yylval->atom = new Atom(82); return ATOM_TOKEN; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 168 "smiles.ll"
{ yylval->atom = new Atom(83); return ATOM_TOKEN; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 169 "smiles.ll"
{ yylval->atom = new Atom(84); return ATOM_TOKEN; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 170 "smiles.ll"
{ yylval->atom = new Atom(85); return ATOM_TOKEN; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 171 "smiles.ll"
{ yylval->atom = new Atom(86); return ATOM_TOKEN; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 172 "smiles.ll"
{ yylval->atom = new Atom(87); return ATOM_TOKEN; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 173 "smiles.ll"
{ yylval->atom = new Atom(88); return ATOM_TOKEN; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 174 "smiles.ll"
{ yylval->atom = new Atom(89); return ATOM_TOKEN; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 175 "smiles.ll"
{ yylval->atom = new Atom(90); return ATOM_TOKEN; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 176 "smiles.ll"
{ yylval->atom = new Atom(91); return ATOM_TOKEN; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 177 "smiles.ll"
{ yylval->atom = new Atom(92); return ATOM_TOKEN; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 178 "smiles.ll"
{ yylval->atom = new Atom(93); return ATOM_TOKEN; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 179 "smiles.ll"
{ yylval->atom = new Atom(94); return ATOM_TOKEN; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 180 "smiles.ll"
{ yylval->atom = new Atom(95); return ATOM_TOKEN; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 181 "smiles.ll"
{ yylval->atom = new Atom(96); return ATOM_TOKEN; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 182 "smiles.ll"
{ yylval->atom = new Atom(97); return ATOM_TOKEN; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 183 "smiles.ll"
{ yylval->atom = new Atom(98); return ATOM_TOKEN; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 184 "smiles.ll"
{ yylval->atom = new Atom(99); return ATOM_TOKEN; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 185 "smiles.ll"
{ yylval->atom = new Atom(100); return ATOM_TOKEN; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 186 "smiles.ll"
{ yylval->atom = new Atom(101); return ATOM_TOKEN; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 187 "smiles.ll"
{ yylval->atom = new Atom(102); return ATOM_TOKEN; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 188 "smiles.ll"
{ yylval->atom = new Atom(103); return ATOM_TOKEN; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 189 "smiles.ll"
{ yylval->atom = new Atom(104); return ATOM_TOKEN; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 190 "smiles.ll"
{ yylval->atom = new Atom(105); return ATOM_TOKEN; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 191 "smiles.ll"
{ yylval->atom = new Atom(106); return ATOM_TOKEN; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 192 "smiles.ll"
{ yylval->atom = new Atom(107); return ATOM_TOKEN; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 193 "smiles.ll"
{ yylval->atom = new Atom(108); return ATOM_TOKEN; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 194 "smiles.ll"
{ yylval->atom = new Atom(109); return ATOM_TOKEN; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 195 "smiles.ll"
{ yylval->atom = new Atom(110); return ATOM_TOKEN; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 196 "smiles.ll"
{ yylval->atom = new Atom(111); return ATOM_TOKEN; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 197 "smiles.ll"
{ yylval->atom = new Atom(112); return ATOM_TOKEN; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 198 "smiles.ll"
{ yylval->atom = new Atom(113); return ATOM_TOKEN; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 199 "smiles.ll"
{ yylval->atom = new Atom(114); return ATOM_TOKEN; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 200 "smiles.ll"
{ yylval->atom = new Atom(115); return ATOM_TOKEN; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 201 "smiles.ll"
{ yylval->atom = new Atom(116); return ATOM_TOKEN; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 202 "smiles.ll"
{ yylval->atom = new Atom(117); return ATOM_TOKEN; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 203 "smiles.ll"
{ yylval->atom = new Atom(118); return ATOM_TOKEN; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 205 "smiles.ll"
{ yylval->atom = new Atom(110); return ATOM_TOKEN; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 206 "smiles.ll"
{ yylval->atom = new Atom(111); return ATOM_TOKEN; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 207 "smiles.ll"
{ yylval->atom = new Atom(112); return ATOM_TOKEN; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 208 "smiles.ll"
{ yylval->atom = new Atom(113); return ATOM_TOKEN; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 209 "smiles.ll"
{ yylval->atom = new Atom(114); return ATOM_TOKEN; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 210 "smiles.ll"
{ yylval->atom = new Atom(115); return ATOM_TOKEN; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 211 "smiles.ll"
{ yylval->atom = new Atom(116); return ATOM_TOKEN; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 212 "smiles.ll"
{ yylval->atom = new Atom(117); return ATOM_TOKEN; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 213 "smiles.ll"
{ yylval->atom = new Atom(118); return ATOM_TOKEN; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 215 "smiles.ll"
{ yylval->atom = new Atom(5);return ORGANIC_ATOM_TOKEN; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 216 "smiles.ll"
{ yylval->atom = new Atom(6);return ORGANIC_ATOM_TOKEN; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 217 "smiles.ll"
{ yylval->atom = new Atom(7);return ORGANIC_ATOM_TOKEN; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 218 "smiles.ll"
{ yylval->atom = new Atom(8);return ORGANIC_ATOM_TOKEN; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 219 "smiles.ll"
{ yylval->atom = new Atom(15);return ORGANIC_ATOM_TOKEN; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 220 "smiles.ll"
{ yylval->atom = new Atom(16);return ORGANIC_ATOM_TOKEN; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 221 "smiles.ll"
{ yylval->atom = new Atom(9);return ORGANIC_ATOM_TOKEN; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 222 "smiles.ll"
{ yylval->atom = new Atom(17);return ORGANIC_ATOM_TOKEN; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 223 "smiles.ll"
{ yylval->atom = new Atom(35);return ORGANIC_ATOM_TOKEN; }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 224 "smiles.ll"
{ yylval->atom = new Atom(53);return ORGANIC_ATOM_TOKEN; }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 226 "smiles.ll"
{
				return H_TOKEN;
			}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 230 "smiles.ll"
{	yylval->atom = new Atom ( 5 );
			yylval->atom->setIsAromatic(true);
				return AROMATIC_ATOM_TOKEN;
			}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 234 "smiles.ll"
{	yylval->atom = new Atom ( 6 );
			yylval->atom->setIsAromatic(true);
				return AROMATIC_ATOM_TOKEN;
			}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 238 "smiles.ll"
{	yylval->atom = new Atom( 7 );
			yylval->atom->setIsAromatic(true);
				return AROMATIC_ATOM_TOKEN;
			}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 242 "smiles.ll"
{	yylval->atom = new Atom( 8 );
			yylval->atom->setIsAromatic(true);
				return AROMATIC_ATOM_TOKEN;
			}
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 246 "smiles.ll"
{	yylval->atom = new Atom( 15 );
			yylval->atom->setIsAromatic(true);
				return AROMATIC_ATOM_TOKEN;
			}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 250 "smiles.ll"
{	yylval->atom = new Atom( 16 );
			yylval->atom->setIsAromatic(true);
				return AROMATIC_ATOM_TOKEN;
			}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 255 "smiles.ll"
{	yylval->atom = new Atom( 14 );
			yylval->atom->setIsAromatic(true);
				return AROMATIC_ATOM_TOKEN;
			}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 259 "smiles.ll"
{	yylval->atom = new Atom( 33 );
			yylval->atom->setIsAromatic(true);
				return AROMATIC_ATOM_TOKEN;
			}
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 263 "smiles.ll"
{	yylval->atom = new Atom( 34 );
			yylval->atom->setIsAromatic(true);
				return AROMATIC_ATOM_TOKEN;
			}
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 267 "smiles.ll"
{	yylval->atom = new Atom( 52 );
			yylval->atom->setIsAromatic(true);
				return AROMATIC_ATOM_TOKEN;
			}
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 272 "smiles.ll"
{   yylval->atom = new Atom( 0 );
		            yylval->atom->setProp(common_properties::dummyLabel,
                                                        std::string("*"));
                                // must be ORGANIC_ATOM_TOKEN because
                                // we aren't in square brackets:
				return ORGANIC_ATOM_TOKEN;
			}
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 280 "smiles.ll"
{ return COLON_TOKEN; }
	YY_BREAK

  // The next block is a workaround for a pathlogy in the SMILES produced
  // by some Biovia tools

case 146:
YY_RULE_SETUP
#line 286 "smiles.ll"
{ yylval->atom = new Atom(104); return ATOM_TOKEN; }
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 287 "smiles.ll"
{ yylval->atom = new Atom(105); return ATOM_TOKEN; }
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 288 "smiles.ll"
{ yylval->atom = new Atom(106); return ATOM_TOKEN; }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 289 "smiles.ll"
{ yylval->atom = new Atom(107); return ATOM_TOKEN; }
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 290 "smiles.ll"
{ yylval->atom = new Atom(108); return ATOM_TOKEN; }
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 291 "smiles.ll"
{ yylval->atom = new Atom(109); return ATOM_TOKEN; }
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 292 "smiles.ll"
{ yylval->atom = new Atom(110); return ATOM_TOKEN; }
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 293 "smiles.ll"
{ yylval->atom = new Atom(111); return ATOM_TOKEN; }
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 294 "smiles.ll"
{ yylval->atom = new Atom(112); return ATOM_TOKEN; }
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 295 "smiles.ll"
{ yylval->atom = new Atom(113); return ATOM_TOKEN; }
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 296 "smiles.ll"
{ yylval->atom = new Atom(114); return ATOM_TOKEN; }
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 297 "smiles.ll"
{ yylval->atom = new Atom(115); return ATOM_TOKEN; }
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 298 "smiles.ll"
{ yylval->atom = new Atom(116); return ATOM_TOKEN; }
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 299 "smiles.ll"
{ yylval->atom = new Atom(117); return ATOM_TOKEN; }
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 300 "smiles.ll"
{ yylval->atom = new Atom(118); return ATOM_TOKEN; }
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 302 "smiles.ll"
{ yylval->bond = new Bond(Bond::DOUBLE);
	  return BOND_TOKEN; }
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 304 "smiles.ll"
{ yylval->bond = new Bond(Bond::TRIPLE);
	  return BOND_TOKEN; }
	YY_BREAK
case 163:
YY_RULE_SETUP
#line 306 "smiles.ll"
{ yylval->bond = new Bond(Bond::AROMATIC);
	  yylval->bond->setIsAromatic(true);
	  return BOND_TOKEN; }
	YY_BREAK
case 164:
YY_RULE_SETUP
#line 309 "smiles.ll"
{ yylval->bond = new Bond(Bond::DATIVER);
	  return BOND_TOKEN; }
	YY_BREAK
case 165:
YY_RULE_SETUP
#line 311 "smiles.ll"
{ yylval->bond = new Bond(Bond::DATIVEL);
	  return BOND_TOKEN; }
	YY_BREAK
case 166:
YY_RULE_SETUP
#line 313 "smiles.ll"
{ yylval->bond = new QueryBond();
	  yylval->bond->setQuery(makeBondNullQuery());
	  return BOND_TOKEN;  }
	YY_BREAK
case 167:
YY_RULE_SETUP
#line 317 "smiles.ll"
{ yylval->bond = new Bond(Bond::SINGLE);
	yylval->bond->setBondDir(Bond::ENDDOWNRIGHT);
	return BOND_TOKEN;  }
	YY_BREAK
case 168:
YY_RULE_SETUP
#line 321 "smiles.ll"
{ yylval->bond = new Bond(Bond::SINGLE);
	yylval->bond->setBondDir(Bond::ENDUPRIGHT);
	return BOND_TOKEN;  }
	YY_BREAK
case 169:
YY_RULE_SETUP
#line 325 "smiles.ll"
{ return MINUS_TOKEN; }
	YY_BREAK
case 170:
YY_RULE_SETUP
#line 327 "smiles.ll"
{ return PLUS_TOKEN; }
	YY_BREAK
case 171:
YY_RULE_SETUP
#line 329 "smiles.ll"
{ return GROUP_OPEN_TOKEN; }
	YY_BREAK
case 172:
YY_RULE_SETUP
#line 330 "smiles.ll"
{ return GROUP_CLOSE_TOKEN; }
	YY_BREAK
case 173:
YY_RULE_SETUP
#line 333 "smiles.ll"
{ BEGIN IN_ATOM_STATE; return ATOM_OPEN_TOKEN; }
	YY_BREAK
case 174:
YY_RULE_SETUP
#line 334 "smiles.ll"
{ BEGIN INITIAL; return ATOM_CLOSE_TOKEN; }
	YY_BREAK
case 175:
YY_RULE_SETUP
#line 336 "smiles.ll"
{ return SEPARATOR_TOKEN; }
	YY_BREAK
case 176:
YY_RULE_SETUP
#line 338 "smiles.ll"
{ return PERCENT_TOKEN; }
	YY_BREAK
case 177:
YY_RULE_SETUP
#line 340 "smiles.ll"
{ yylval->ival = 0; return ZERO_TOKEN; }
	YY_BREAK
case 178:
YY_RULE_SETUP
#line 341 "smiles.ll"
{ yylval->ival = atoi( yytext ); return NONZERO_DIGIT_TOKEN; }
	YY_BREAK
case 179:
/* rule 179 can match eol */
YY_RULE_SETUP
#line 345 "smiles.ll"
return 0;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IN_ATOM_STATE):
#line 347 "smiles.ll"
{ return EOS_TOKEN; }
	YY_BREAK
case 180:
YY_RULE_SETUP
#line 348 "smiles.ll"
return yytext[0];
	YY_BREAK
case 181:
YY_RULE_SETUP
#line 350 "smiles.ll"
ECHO;
	YY_BREAK
#line 1980 "/scratch/RDKit_git/Code/GraphMol/SmilesParse/lex.yysmiles.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yysmiles_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yysmiles_wrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yysmiles_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	yy_size_t number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yysmiles_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yysmiles_restart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yysmiles_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 246 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 246 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 245);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp , yyscan_t yyscanner)
{
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_cp = yyg->yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yyg->yy_hold_char;

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = yyg->yy_n_chars + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	yyg->yytext_ptr = yy_bp;
	yyg->yy_hold_char = *yy_cp;
	yyg->yy_c_buf_p = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yy_size_t offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yysmiles_restart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yysmiles_wrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yysmiles_restart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yysmiles_ensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yysmiles__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	yysmiles__init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	yysmiles__load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yysmiles__switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yysmiles_pop_buffer_state();
	 *		yysmiles_push_buffer_state(new_buffer);
     */
	yysmiles_ensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yysmiles__load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yysmiles_wrap()) processing, but the only time this flag
	 * is looked at is after yysmiles_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yysmiles__load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yysmiles__create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yysmiles_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yysmiles__create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yysmiles_alloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yysmiles__create_buffer()" );

	b->yy_is_our_buffer = 1;

	yysmiles__init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yysmiles__create_buffer()
 * @param yyscanner The scanner object.
 */
    void yysmiles__delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yysmiles_free((void *) b->yy_ch_buf ,yyscanner );

	yysmiles_free((void *) b ,yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yysmiles_restart() or at EOF.
 */
    static void yysmiles__init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yysmiles__flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yysmiles__init_buffer was _probably_
     * called from yysmiles_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yysmiles__flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yysmiles__load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yysmiles_push_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yysmiles_ensure_buffer_stack(yyscanner);

	/* This block is copied from yysmiles__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yysmiles__switch_to_buffer. */
	yysmiles__load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yysmiles_pop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yysmiles__delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yysmiles__load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yysmiles_ensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yysmiles_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yysmiles_ensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yysmiles_realloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yysmiles_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yysmiles__scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yysmiles_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yysmiles__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yysmiles__switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yysmiles_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yysmiles__scan_bytes() instead.
 */
YY_BUFFER_STATE yysmiles__scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return yysmiles__scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yysmiles_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yysmiles__scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yysmiles_alloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yysmiles__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yysmiles__scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yysmiles__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yysmiles_get_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yysmiles_get_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yysmiles_get_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yysmiles_get_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yysmiles_get_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
yy_size_t yysmiles_get_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yysmiles_get_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yysmiles_set_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yysmiles_set_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yysmiles_set_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yysmiles_set_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yysmiles_set_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yysmiles__switch_to_buffer
 */
void yysmiles_set_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yysmiles_set_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yysmiles_get_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yysmiles_set_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * yysmiles_get_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void yysmiles_set_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

/* User-visible API */

/* yysmiles_lex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int yysmiles_lex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yysmiles_alloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yysmiles_lex_init_extra has the same functionality as yysmiles_lex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yysmiles_alloc in
 * the yyextra field.
 */

int yysmiles_lex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    yysmiles_set_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) yysmiles_alloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    yysmiles_set_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yysmiles_lex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yysmiles_lex_init()
     */
    return 0;
}

/* yysmiles_lex_destroy is for both reentrant and non-reentrant scanners. */
int yysmiles_lex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yysmiles__delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yysmiles_pop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yysmiles_free(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yysmiles_free(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yysmiles_lex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yysmiles_free ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yysmiles_alloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return (void *) malloc( size );
}

void *yysmiles_realloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yysmiles_free (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yysmiles_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 350 "smiles.ll"



#undef yysmiles_wrap
int yysmiles_wrap( void ) { return 1; }

