from typing import overload

import rdkit.Chem.rdchem


class MolCatalog:
    def __init__(self, pickle: bytes) -> None: ...

    def GetNumEntries(self) -> int: ...

    def GetFPLength(self) -> int: ...

    def Serialize(self) -> bytes: ...

    def GetBitDescription(self, idx: int) -> str: ...

    def GetBitEntryId(self, idx: int) -> int: ...

    def GetEntryBitId(self, idx: int) -> int: ...

    def GetEntryDescription(self, idx: int) -> str: ...

    def GetEntryDownIds(self, idx: int) -> list[int]: ...

    def AddEntry(self, entry: MolCatalogEntry) -> int: ...

    def AddEdge(self, id1: int, id2: int) -> None: ...

    def __getstate__(self) -> tuple[bytes]: ...

    @overload
    def __setstate__(self, arg: tuple[bytes], /) -> None: ...

    @overload
    def __setstate__(self, arg: tuple[str], /) -> None: ...

class MolCatalogEntry:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, pickle: bytes) -> None: ...

    def GetDescription(self) -> str: ...

    def SetDescription(self, val: str) -> None: ...

    def GetMol(self) -> rdkit.Chem.rdchem.Mol: ...

    def SetMol(self, mol: rdkit.Chem.rdchem.Mol) -> None: ...

    def GetOrder(self) -> int: ...

    def SetOrder(self, order: int) -> None: ...

    def Serialize(self) -> bytes: ...

    def __getstate__(self) -> tuple[bytes]: ...

    @overload
    def __setstate__(self, arg: tuple[bytes], /) -> None: ...

    @overload
    def __setstate__(self, arg: tuple[str], /) -> None: ...

def CreateMolCatalog() -> MolCatalog: ...
