steps:
- bash: |
    wget https://github.com/phracker/MacOSX-SDKs/releases/download/10.15/MacOSX$(target_platform).sdk.tar.xz
    tar Jxvf MacOSX$(target_platform).sdk.tar.xz
  displayName: Install MacOSX $(target_platform) SDK
- script: |
    echo "Removing homebrew from Azure to avoid conflicts."
    curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
    chmod +x ~/uninstall_homebrew
    ~/uninstall_homebrew -fq
    rm ~/uninstall_homebrew
  displayName: Remove homebrew
- bash: |
    source ${CONDA}/etc/profile.d/conda.sh
    sudo chown -R ${USER} ${CONDA}
    mkdir -p $HOME/.matplotlib
    echo -e "backend: TkAgg\n" > $HOME/.matplotlib/matplotlibrc
    conda config --set always_yes yes --set changeps1 no
    conda update -q conda
    conda create --name rdkit_build $(compiler) cmake \
        boost-cpp=$(boost_version) boost=$(boost_version) \
        py-boost=$(boost_version) libboost=$(boost_version) \
        cairo eigen
  displayName: Setup build environment
- bash: |
    source ${CONDA}/etc/profile.d/conda.sh
    conda activate rdkit_build
    export CONDA_BUILD_SYSROOT=${SDKROOT}

    export SANITIZER_FLAGS_address="-fsanitize=address -fsanitize-address-use-after-scope"
    export COVERAGE_FLAGS="-fsanitize=fuzzer-no-link"
    export CFLAGS="-O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION $COVERAGE_FLAGS $SANITIZER_FLAGS_address"
    export CXXFLAGS_EXTRA="-stdlib=libc++"
    export CXXFLAGS="$CFLAGS $CXXFLAGS_EXTRA"
    export LIB_FUZZING_ENGINE="-fsanitize=fuzzer"

    mkdir build && cd build && \
    cmake .. \
    -DCMAKE_BUILD_TYPE=Release \
    -DRDK_INSTALL_INTREE=ON \
    -DRDK_BUILD_PYTHON_WRAPPERS=OFF \
    -DLIB_FUZZING_ENGINE=${LIB_FUZZING_ENGINE} \
    -DRDK_BUILD_FUZZ_TARGETS=ON \
    -DRDK_INSTALL_STATIC_LIBS=ON \
    -DBoost_USE_STATIC_LIBS=ON \
    -DRDK_BUILD_CPP_TESTS=OFF \
    -DBoost_NO_SYSTEM_PATHS=ON \
    -DCMAKE_INCLUDE_PATH="${CONDA_PREFIX}/include" \
    -DCMAKE_LIBRARY_PATH="${CONDA_PREFIX}/lib" \
    -DCMAKE_PREFIX_PATH=$CONDA_PREFIX
  displayName: Configure build (Run CMake)
- bash: |
    source ${CONDA}/etc/profile.d/conda.sh
    conda activate rdkit_build
    export CONDA_BUILD_SYSROOT=${SDKROOT}
    cd build
    make -j $( $(number_of_cores) ) install
  displayName: Build
- script: |
    cd build
    shopt -s globstar
    corpora=**/*_fuzzer/
    for corpus in $corpora; do
      corpus_basename=$(basename $corpus)
      ${corpus_basename} ${corpus}/*
    done
  displayName: Run fuzzer on existing corpora
