name: Build MinimalLib WASM

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Dockerfile_1_deps
        uses: docker/build-push-action@v5
        with:
          context: ./Code/MinimalLib/docker
          file: Code/MinimalLib/docker/Dockerfile_1_deps
          outputs: type=local,dest=dist
          push: false

      - name: Build Dockerfile_2_src
        uses: docker/build-push-action@v5
        with:
          context: ./Code/MinimalLib/docker
          file: Code/MinimalLib/docker/Dockerfile_2_rdkit_copy_from_local
          outputs: type=local,dest=dist
          push: false

      - name: Build Dockerfile_3_build
        uses: docker/build-push-action@v5
        with:
          context: ./Code/MinimalLib/docker
          file: Code/MinimalLib/docker/Dockerfile_3_rdkit_build
          outputs: type=local,dest=dist
          push: false

