name: Build MinimalLib WASM

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build WASM assets
        uses: docker/build-push-action@v5
        with:
          context: ./Code/MinimalLib
          file: Code/MinimalLib/docker/Dockerfile_1_deps
          outputs: type=local,dest=dist
          push: false

