name: Pull molecular templates header updates
on:
  workflow_dispatch: ~
  schedule:
    # Run every Sunday at 00:00 UTC
    - cron: '0 0 * * 6'

permissions:
  contents: write
  pull-requests: write

env:
  tpl_repo: 'ricrogz/molecular_templates'
  tpl_hdr: 'template_smiles.h'
  rdk_hdr: 'Code/GraphMol/Depictor/TemplateSmiles.h'

jobs:
  check_header_changes_and_create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout RDKit
        uses: actions/checkout@v3
      - name: Checkout molecular_templates
        uses: actions/checkout@v3
        with:
            repository: ${{ env.tpl_repo }}
            ref: main
            path: molecular_templates
      - name: Check for header changes
        id: header-check
        run: |
            cp -f molecular_templates/${{ env.tpl_hdr }} ${{ env.rdk_hdr }}
            header_changed=$(git diff --name-only ${{ env.rdk_hdr }} | wc -l)
            echo "header_changed=${header_changed}" >> ${GITHUB_OUTPUT}
            templates_sha=$(cd molecular_templates && git rev-parse --short HEAD)
            echo "templates_sha=${templates_sha}" >> ${GITHUB_OUTPUT}
      - name: Commit the new header file to RDKit branch
        if: ${{ steps.header-check.outputs.header_changed == '1' && success() }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
            repository: rdkit
            branch: ${{ format('templates_update_{0}', steps.header-check.outputs.pr_branch) }}
            create_branch: true
            commit_message: "[bot] Update molecular templates header"
            file_pattern: ${{ env.rdk_hdr }}
      - name: pull-request-action
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_FROM_BRANCH: ${{ format('templates_update_{0}', steps.header-check.outputs.pr_branch) }}
          PULL_REQUEST_BRANCH: "master"
          PULL_REQUEST_BODY: ${{ format('Automated Pull Request to update molecular templates for
             coordinate generation to header in commit {0} \#{1}', env.tpl_repo,
            steps.header-check.outputs.pr_branch) }}
          PULL_REQUEST_TITLE: "[bot] Update molecular templates header file"
          MAINTAINER_CANT_MODIFY: "true"